name: jetleaf_convert
description: Provides dynamic type conversion utilities for JetLeaf applications.
version: 1.0.0+2

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_convert
issue_tracker: https://github.com/jetleaf/jetleaf_convert/issues
documentation: https://jetleaf.hapnium.com/docs/convert

topics:
  - conversion
  - mapping
  - serialization
  - jetleaf
  - adapters

keywords:
  - conversion
  - converters
  - adapters
  - serialization
  - jetleaf

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: 
    path: ../jetleaf_lang

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0