name: jetleaf_convert
description: A library that provides high-level of conversion for the Jetleaf application. It powers the conversion of types to the target types based on request.
version: 1.0.0

publish_to: none

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_convert

topics:
- Conversion Service
- Converters
- Dynamic conversion

keywords:
- Conversion Service
- Converters
- Dynamic conversion

environment:
  sdk: ^3.9.0

dependencies:
  jetleaf_lang:
    path: ../jetleaf_lang

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0